# creation_rules:
#   - path_regex: \.yaml$
#     key_groups:
#       - pgp:
#           - "015F6F8E327A9C34"
#
creation_rules:
  - filename_regex: .*
    key_groups:
      - pgp:
          - "015F6F8E327A9C34"
